name: Giku Debug Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Set up Android SDK
        uses: android-actions/setup-android@v2

      - name: Fix Gradle Wrapper Permissions
        run: chmod +x ./gradlew

      - name: Extract Version
        id: version
        run: |
          VERSION=$(./gradlew -q printVersionName)
          echo "version=${VERSION}" >> $GITHUB_OUTPUT

      - name: Build Debug APK
        run: ./gradlew assembleDebug

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v3
        with:
          name: giku-debug-apk
          path: app/build/outputs/apk/debug/*.apk